language: ruby

rvm:
  - 2.6.3

services:
  - postgresql

before_install:
  - bundle install
  - psql -c 'create database travis_ci_test;' -U postgres

before_script:
  - RAILS_ENV=test rake db:migrate
  - rake db:migrate
  - bin/yarn

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn install

script:
  - yarn test
  - bundle exec rspec spec

after_success:
  - ./bin/webpack
  - bundle exec rails webpacker:compile

deploy:
  provider: heroku
  api_key:
    secure: iCqmTp8NNzWrfN5DJJ2/BHplRBfgmGE2JI0AFRblQk+zV7k7sQAVG4p08pUdi89sIDMUqX5CHBd0uAAY0Ychv00/sWmFV/dOpH2L48CpMrVNxE8rdgIzulYrouX/G2/2kne16fLPVvV3vxw/jEqgrM0Nx8ee0hqD9iMMRRj/ocDErwg10bXCEjSVbPxQ2Zz0xIKJLHjvyGovkUH5n5dnRpQpwigMU1hEbxiubREVLz0VOXr4HSW2fmXx2NKcT1YexqYBqFRv1H2wWEQmLpzB/QdtTMokO6sNVCOXNOuspsfzhEZoSYAWiNal4kWAwZ2/Jn2eoncuV9/Ks3tCeEk/NE7+w+Sx9w2vI88AvJjMaLaBBgiNmAUsSYzKURBazX5Tf7HrqCCNJAKZ+G+1xe89j2lCEMN/pm3kiSQjnjLIwbdbn4CyEIEBXV+iLPye77jPLGst3ecWeBVbFcvzO+7zqW3JgfJhpbQKuV+eNkpb1yuOP9weBFrnmR1ZEb98yFfRzGQNnB5rQOV5Eo7AyqsVtnvcUyaUPTk6CiI7JJ3GEj5pgz8tmEFeD+NuL8VrN6qjR16j2J2Hrt1jvBWkK4EFvTeFTfF9eKXbUeQWwBb+cSOOQZm5s7vMfnexcIHV86PdfF3wFHV03f1Gh0xlZusaai7g7/uFu+LRD8Zr2sRl+UI=
  app: tickettalk
  on:
    repo: evettetelyas/tbd

  run:
    - "rake db:migrate"
