language: ruby

rvm:
  - 2.6.3

addons:
  homebrew:
    packages:
      - yarn

services:
  - postgresql

before_install:
  - bundle install
  - psql -c 'create database travis_ci_test;' -U postgres

before_script:
  - RAILS_ENV=test rake db:migrate
  - rake db:migrate
  - bin/yarn

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - yarn add node@10
  - yarn install

script:
  - bundle exec rspec spec

after_success:
  - ./bin/webpack
  - bundle exec rails webpacker:compile
